version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: userdb
      MONGO_INITDB_ROOT_PASSWORD: pass123
    networks:
      - network-parceiroze

  mongo-seed:
    container_name: mongo-seed
    build: ./mongo-seed
    depends_on:
      - mongodb
    networks:
      - network-parceiroze

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: userdb
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass123
      ME_CONFIG_MONGODB_URL: mongodb://userdb:pass123@mongo:27017/
    networks:
      - network-parceiroze

  redis-cache:
    image: redis
    container_name: redis-cache
    hostname: redis-cache
    command: ["redis-server", "--protected-mode", "no", "--bind", "0.0.0.0", "--port", "6379"]
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB, FLUSHALL
    ports:
      - 6379:6379
    networks:
      - network-parceiroze

  application:
    container_name: ze-delivery-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://userdb:pass123@mongo:27017/
      - REDIS_URL=redis-cache
      - AMBIENTE=dev
    ports:
      - "8085:8085"
    mem_limit: 512m
    depends_on:
      - mongodb
      - redis-cache
    links:
      - mongodb
      - redis-cache
    networks:
      - network-parceiroze

networks:
  network-parceiroze:
    driver: bridge