version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: userdb
      MONGO_INITDB_ROOT_PASSWORD: pass123

  mongo-seed:
    container_name: mongo-seed
    build: ./mongo-seed
    depends_on:
      - mongodb

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: userdb
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass123
      ME_CONFIG_MONGODB_URL: mongodb://userdb:pass123@mongo:27017/
